### ISSUE TITLE
How to set systemProperty ?

### ISSUE THREAD

**Issue by ghost** [liblit/simple-jni#1]
https://github.com/liblit/simple-jni/blob/master/build.gradle

This file contains system properties. 

Will this set up work on Windows,  Linux and mac ?

**Comment by liblit** [comment]
You can see [here](https://github.com/liblit/simple-jni/blob/master/.travis.yml#L4-L10) that I test on both Linux and macOS. The green check mark [here](https://github.com/liblit/simple-jni/commit/31131663b4c0aceb50a89582e6a1a2f8102776f1) shows that all tests passed as of the most recent commit. I cannot say whether Windows works or not, since that's not a tested platform.

Be aware, though, that the most recent commit to this repository was more than three years ago. Host platforms evolve, as does Gradle itself. The way things are set up in this repository may have been correct three years ago, but I doubt that I'd do it the same way today. I recommend that you look for more recent examples elsewhere.

**Comment by poorvajappja** [comment]
How can I set systemProperty java.library.path ?
I added the following code in gradle.build file to set systemProperty.
task local { run { systemProperty "java.library.path", file("${project(":hello").buildDir}/lib/main/debug").absolutePath } } bootRun.mustRunAfter local 
But , it not worked.
How can I set systemProperty java.library.path in gradle.build file ?
